# Generated by Django 3.1.7 on 2021-03-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quatity', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buy_date', models.DateField()),
            ],
        ),
    ]
