# Generated by Django 3.1.7 on 2021-03-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buy_date',
            field=models.DateTimeField(),
        ),
    ]
