# Generated by Django 3.1.7 on 2021-03-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210320_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
