# Generated by Django 3.1.7 on 2021-04-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210320_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
