# Generated by Django 3.1.7 on 2022-01-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210404_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='yangon', max_length=50),
            preserve_default=False,
        ),
    ]
